version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: "postgres"
    restart: always
    profiles:
      - deploy
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORTS}

  postgres_debug:
    image: postgres:16
    container_name: "postgres"
    restart: always
    profiles:
      - debug
    volumes:
      - pgdebugdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORTS}

  redis:
    image: redis:alpine
    container_name: "redis"
    restart: always
    profiles:
      - debug
      - deploy
    ports:
      - ${REDIS_PORTS}
    environment:
      REDIS_HOST: ${REDIS_HOST}

  articles-api:
    build: .
    container_name: "articles"
    restart: always
    profiles:
      - deploy
    depends_on:
      - postgres
      - redis
    ports:
      - ${SPRING_PORTS}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_FLYWAY_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_USER: ${POSTGRES_USER}
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}

      TOKEN_SIGNING_KEY_ACCESS: ${TOKEN_SIGNING_KEY_ACCESS}
      TOKEN_SIGNING_KEY_REFRESH: ${TOKEN_SIGNING_KEY_REFRESH}

volumes:
  pgdata:
    name: pgdata
  pgdebugdata:
    name: pgdebugdata