version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: articles
    ports:
      - "1111:5432"

  redis:
    image: redis
    container_name: "redis"
    restart: always
    ports:
      - "2222:6379"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  
  articles-api:
    build: .
    container_name: "articles"
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/articles
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379