spring:
  mvc:
    log-resolved-exception: false
  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}
      time-to-live: 2592000
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USER}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
  flyway:
    url: ${LOCAL_DATASOURCE_URL}
    user: ${LOCAL_DATASOURCE_USER}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always
token:
  signing:
    key:
      access: ${TOKEN_SIGNING_KEY_ACCESS}
      refresh: ${TOKEN_SIGNING_KEY_REFRESH}
    time:
      access: 3600000
      refresh: 2592000000
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
    enabled-by-default: true
